site_name: fastgeoapi
docs_dir: docs
site_dir: docs_build/site

repo_name: "geobeyond/fastgeoapi"
repo_url: "https://github.com/geobeyond/fastgeoapi"
# edit_uri: "blob/main/docs/src/"
# site_url: "https://developmentseed.org/titiler/"


theme:
  name: material
  palette:
    primary: indigo
    scheme: default


nav:
  - fastgeoapi: "index.md"
  - User Guide:
    - Intro: "intro.md"
    - Starting Server : "pages/userGuide/start.md"
  - Other links: 
    - Contributing : "pages/other/contributing.md"